version: '3,8'
services:
  telegram-bot:
    image: telegram-echo-bot:latest
    env_file: .env
    environment:
      - "SERVER_URL=jdbc:postgresql://db:5432/echo_bot_db"
      - "SERVER_USERNAME=user"
      - "SERVER_PASS=pass"
      - "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}"
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: echo_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d echo_bot_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  postgres_data: