spring:
  application:
    name: TelegramBerkutBot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SERVER_URL:jdbc:postgresql://localhost:5432/first_db}
    username: ${SERVER_USERNAME:postgres}
    password: ${SERVER_PASS:1322}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  telegram:
    name: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
    commands:
      bind: "/bind "
      unbind: "/unbind"
    messages:
      bind:
        success: "Чат успешно привязан к аккаунту!"
      unbind:
        success: "Чат успешно отвязан от аккаунта!"
      error:
        invalid-token: "Неверный токен!"
        token-already-bound: "Чат уже привязан!"
        internal-error: "Ошибка сервера. Попробуйте позже."
        default-message: "Неизвестная команда. Список команд('/bind ','/unbind')"
  api:
    security:
      token:
        length: 32
      jwt:
        secret-key: 7738782F425432A462D413F44284614E7235757635266556A5867217AAE32743
        expiration: 86400000 # a day
    messages:
      echo: "%s, я получил от тебя сообщение:\n%s"

server:
  port: 8088